services:
  wordpress:
    image: wordpress:php8.3
    restart: always
    ports:
      - "0.0.0.0:8080:80" # 🟢 Открываем порт 8080
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - .:/var/www/html # 🟢 Подключаем ВСЕ файлы проекта
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini # 🟢 Подключаем настройки PHP
      # - /var/www/html/wp-content # 🟢 Исключаем system-файлы WordPress (иначе могут быть ошибки)
      # - ./wp-content:/var/www/html/wp-content # 🟢 Подключаем контент
      # - ./uploads:/var/www/html/wp-content/uploads # 🟢 Подключаем папку uploads

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"  # Открываем MySQL для TablePlus
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
